language: node_js
node_js:
  - "9.2"
before_install:
  - export DISPLAY=:99.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - make test
